### PR TITLE
Add new functionality 'swipe to open/close menu'

### PR DESCRIPTION
**Pull request by casevictor**
Now we can use the swipe gesture to open/close the menu at any point of main screen.

### CODE REVIEW

**Comment by ricardoalcocer** [comment]
Like it!

Haven't tried on iOS device, but on Simulator and on Android device swipe only works after you've opened the menu manually at least once.

**Comment by casevictor** [comment]
@ricardoalcocer thank you :)
Have you tried with the commit that add exports.menuOpen=menuOpen; to widget?
I tested again, and here works fine o.O

**Comment by ricardoalcocer** [comment]
So are there changes needed in the host controller?  Could you copy the Widget for the "demo" and "simple" app and make those changes?  All I did was clone YOUR repo and copy the widget to the demo app.

**Comment by ricardoalcocer** [comment]
Know what I'm thinking? The swipe functionality should not be in the controller of the host app, but inside the widget itself, something like $.drawermenu.setSwipe($.index);

But what could be even better is to change the widget interface so it is like:

$.drawermenu.init({
    menuview: mymenuview,
    mainview: mymainview,
    parent: $.index
})

I'll give it some thought.

**Comment by casevictor** [comment]
Uhmm.. it's true! Can you help me with this?
For now, with the commit's, works for you?

**Comment by ricardoalcocer** [comment]
Yes...I'm looking at it right now....it shouldn't be too hard.

**Comment by casevictor** [comment]
Great!

**Comment by ricardoalcocer** [comment]
Want to give it a try with this version?

**Comment by casevictor** [comment]
Yes! i will try it :+1:

**Comment by ricardoalcocer** [comment]
Did it work for you?

**Pull request merged**
