### PR TITLE
Added Event Handles for open and close menu events

### PR DESCRIPTION
**Pull request by danpe**
Added Event Handles for open and close menu events

### CODE REVIEW

**Comment by ricardoalcocer** [comment]
Thanks!

Could you please add the change to the sample apps so everything is in sync?

**Comment by danpe** [comment]
Hey np,

Where should I add it "**ActionBar Demo**" / "**demo**" / "**simple**" ?

**Comment by ricardoalcocer** [comment]
Yes please.

**Comment by danpe** [comment]
Added :)

**Comment by ricardoalcocer** [comment]
Thank you!

R

**Pull request merged**
